modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/crispytwig/Pooped/issues"

[[mods]]
modId = "pooped"
version = "${version}"
displayName = "pooped"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pooped"
logoFile = "icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "Crispytwig, Synthestra"
description = '''
Poop
'''

[[dependencies.pooped]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pooped]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
